### ISSUE TITLE
typo in off-axis field due to a current loop latex equations

### ISSUE THREAD

**Issue by ale-mendez** [tiggerntatie/emagnet-py#1]
Hi! 

I just wanted to let you know that int the latex equations of Bx and Br, E and K show a linear dependence of k, instead of k^2.

Also, your git is awesome. Thanks!

**Comment by jonathanschilling** [comment]
@ale-mendez There are various definitions of complete elliptic integrals; some imply a quadratic argument and some don't.

See for example https://en.wikipedia.org/wiki/Elliptic_integral#Notational_variants :
> Moreover, their complete integrals employ the parameter k2 as argument in place of the modulus k, i.e. K(k2) rather than K(k)

**Comment by FLFNick** [comment]
I also fell foul of this. It seems like you might be saying that the notation implies that it should be k squared but this was very much not obvious to me. A comment to clarify would be super helpful. Otherwise, this is a great resource, thanks for doing it!

**Comment by tiggerntatie** [comment]
I appreciate the input on this @FLFNick, @ale-mendez, and @jonathanschilling! I have updated the page with a note of caution.
